### PR TITLE
Feature/native json object

### PR DESCRIPTION
**Pull request by bundeskanzler4711**
According to https://github.com/google/openrtb/issues/85 this is my pull request.

Bid request:
  - no root-native field, native as request field (String)
  - including root-native field, native as request field (String)
  - no root-native field, native as request_native field (Json-Object) **NEW**
  - including root-native field, native as request_native field (Json-Object) **NEW**

Bid response:
  - no root-native field, native as adm field (String)
  - including root-native field, native as adm field (String)
  - no root-native field, native as adm_native field (Json-Object) **NEW**
  - including root-native field, native as adm_native field (Json-Object) **NEW**

### CODE REVIEW

**Comment by bundeskanzler4711** [comment]
I signed it!

googlebot <notifications@github.com> schrieb am Mi., 18. Mai 2016 um
14:54 Uhr:

**Comment by bschev** [comment]
I signed it!

2016-05-18 15:02 GMT+02:00 googlebot <notifications@github.com>:

**Comment by bundeskanzler4711** [comment]
Test

**Comment by bundeskanzler4711** [comment]
It's a mistake, only @bschev and @bundeskanzler4711 contributed to this pull request

**Comment by bundeskanzler4711** [comment]
confirm

googlebot <notifications@github.com> schrieb am Mi., 18. Mai 2016 um
15:32 Uhr:

**Comment by bschev** [comment]
I confirm that I authored some of the commits.

**Comment by bundeskanzler4711** [comment]
Test 2

**Comment by bundeskanzler4711** [comment]
conflict -> close.

**Pull request closed without merging**
