### PR TITLE
Update openrtb.pro with latest specs from Open RTB 2.4 / Native 1.1

### PR DESCRIPTION
**Pull request by torbenbrodt**
I have implemented ContextTypeId + ContextSubTypeId + PlacementTypeId

Those are available from 
* OpenRTB Dynamic Native Ads API, Specification Version 1.1, March 2016 <http://www.iab.com/wp-content/uploads/2016/03/OpenRTB-Native-Ads-Specification-1-1_2016.pdf>
* OpenRTB API Specification Version 2.4, FINAL DRAFT, March 2016 <http://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-4-FINAL.pdf>

Google Contributor License Agreement has been signed

### CODE REVIEW

**Comment by opinali** [comment]
Hi @torbenbrodt, first thanks for the contribution! However there are some problems with accepting this (mostly our own fault). It turns out that we already have the full 2.4/1.1 proto changes internally at Google, but the actual support for the new protocol in AdX is still work in progress... and even though this library is exchange-neutral, in practice it's derived from AdX/OpenRTB since we started supporting the protocol natively this year. And while this project welcomes external fixes and contribs, the proto is a critical piece that needs to match the internal stuff exactly. (It's a perfect copy of [this file](https://developers.google.com/ad-exchange/rtb/downloads/openrtb-proto), except for the license header.)

Other minor issue: The numeric tag ID for existing fields (like `assets`) cannot change, ever, in no circumstance, it's a dogmatic rule for us because protobuf relies on this for compatibility across versions.

But I'll take this as incentive for moving faster with 2.4/1.1, this shouldn't really be gated on AdX's full support (which is reflected by a [separate library](https://github.com/google/openrtb-doubleclick)). So what I'm doing now is updating the proto here with our latest internal changes, so that this library will have the more up-to-date proto, and the copy at the AdX download site will stick to 2.3/1.0 for now.

**Comment by torbenbrodt** [comment]
Hey Osvaldo, I am happy for the fast response and looking forward to the updated .proto file. Thanks a lot.

**Comment by opinali** [comment]
You can take an early look at the upcoming support for 2.4/1.1 [here](https://github.com/opinali/openrtb/commit/334c9f8a08912dc2b41231da63c65c728a32a39d). Unfortunately this will require some breaking changes, but only imports.

**Comment by opinali** [comment]
I'm closing this PR, and opened a bug to track 2.4/1.1 impl :)

**Pull request closed without merging**
