### PR TITLE
Represent prices as integers internally

### PR DESCRIPTION
**Pull request by metaquanta**
These numbers are represented as decimals in the json. However, that does not imply they are floats. The spec even specifies, as duplicated in openrtb.proto, that "WARNING/Best Practice Note: Although this value is a float, OpenRTB strongly suggests using integer math for accounting to avoid rounding errors."
I have changed their internal representation to millionths of currency unit.

### CODE REVIEW

**Comment by opinali** [comment]
@metaquanta thanks for the patch! I just wish we had discussed this before writing the code. The problem is that storing values as decimals is not really helpful unless values are manipulated as decimals everywhere in the application that uses the library; using decimals only for storage or in parse/format operations makes no difference if apps still have to call getters/setters that only use doubles. And of course we can't have a `BigDecimal` in the API because protobuf doesn't support any type that maps to `BigDecimal` or equivalent language-specific decimal types.

I considered using a `string` field for these values, but that would result in a really inconvenient API, forcing every get/set call to perform a conversion. And this still wouldn't provide any advantage over doubles: today you can just write code like `BigDecimal bidfloor = new BigDecimal(imp.getBidfloor)`. The double field is precise enough to represent any price; it supports 15-17 significant decimal digits of mantissa, and more critically, for any numbers up to 15 digits roundtrip conversions between a string (or precise decimal type) and a double are guaranteed to always be exact. This means `double` is perfectly safe for storage and parsing/formatting of any normal value used in OpenRTB.

The above is for background; now specifically on your patch: you're changing the model's field types to `int64` (= Java's `long`), and changing their scale to micros (just like DoubleClick's native protocol). This is another way to solve the problem, but then it forces apps to always manipulate prices in micros instead of "currency units" (USD or whatever used by the request). Unfortunately this is even more inconvenient for users of the API; as an end-user myself, if I care about precise decimal arithmetics I'd rather make some explicit `double`/`BigDecima`l conversions than work with micros all the time.

Technically, OpenRTB defines only a wire protocol and we have some flexibility for API/language-binding design, see for example how this library uses booleans instead of 0/1 integers for flags; or how I have introduced an extended `admNative` field [native is still WIP]. But these are changes that make the API significantly more type-safe and easy to use. The `admNative` will also result in significant performance gain. Changing the price to micros is a step backward in usability. (Also an important breaking change, one I'd rather avoid at this time, this code already has significant usage...) Even the potential advantage of precision is highly questionable, because `double` is not only good enough for storage and conversions, it's good enough even for arithmetics, since the values we manipulate here leave lots of mantissa bits unused – you'd need a crapton of error propagation before you get a significant error (I doubt any SSP or other platform will consider digits below 1^-6). This is remarkably true for monetary values, which are typically only manipulated by simple operations like sums or multiplies, which have maximum precision (<= 1ulp) in any language or platform; few if any people should calculate bid prices with complex formulas full of transcendental operations that sometimes have several bits of error in some "hard" value ranges. And if anyone is doing that, they certainly can't use `long`: even `BigDecimal` would be a huge ordeal because in most mainstream languages – anything other than specialized stuff like Mathematica – the math libraries cannot perform any decent math with decimal types; anything as sophisticated as a square root forces you to step down to floating point anyway.

Having said all that, my only concern with the current, simple usage of `double` is in the serialization; for example it would be ugly (although not a real problem) if the library emits JSON like `price: "1.2000000000000000000003"` due to accumulation of errors in the last few bits. Ideally, (1) the code for deserialization should ignore anything after some specific limit like the sixth digit after the decimal point, (2) the code for serialization should make sure to only emit digits up to the same limit. I think Java's default behavior in `double`/`String` conversions will take care of (2) but I'm not sure at which digit, and it won't take care of (1) at all. We could use `BigDecimal` to solve these problems, but I think just the `DecimalFormat` API should be good enough for that and way more efficient.

**Comment by metaquanta** [comment]
My limited time investment was absolutely worth getting to read such a
thorough justification for the existing implementation. Thanks a lot for
the response. I'm glad to see the degree to which you've considered the
problem.

I am a user and we handle everything as micros. I find the necessary
conversions objectionable and now you've convinced me it is only an
aesthetic objection.

I share your concern regarding (de)serialization. However, in practice I
feel that's also unlikely to result in any real unwanted behavior outside
of a human eavesdropper scratching their head.

Thanks a lot for the response!
Matt

**Comment by opinali** [comment]
Thanks for the understanding! I'm closing the request then, but keeping this in mind. Just curious if your current habit of using micros for everything comes from working with the DoubleClick protocol?

**Comment by metaquanta** [comment]
I have not used the DoubleClick protocol, but it's probably somewhere in
the heritage of code I've worked on.

**Pull request closed without merging**
